# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: master_health_interface.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'master_health_interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dmaster_health_interface.proto\x12\x0fmaster_internal\"\x7f\n\x0eWorkerLoadInfo\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x17\n\x0f\x63pu_utilization\x18\x02 \x01(\x02\x12\x14\n\x0c\x61\x63tive_tasks\x18\x03 \x01(\x05\x12\x1a\n\x12memory_usage_bytes\x18\x04 \x01(\x03\x12\x11\n\tworker_id\x18\x05 \x01(\t\"\x1a\n\x18GetHealthyWorkersRequest\"W\n\x19GetHealthyWorkersResponse\x12:\n\x11workers_with_load\x18\x01 \x03(\x0b\x32\x1f.master_internal.WorkerLoadInfo2\x83\x01\n\x15InternalMasterService\x12j\n\x11GetHealthyWorkers\x12).master_internal.GetHealthyWorkersRequest\x1a*.master_internal.GetHealthyWorkersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'master_health_interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKERLOADINFO']._serialized_start=50
  _globals['_WORKERLOADINFO']._serialized_end=177
  _globals['_GETHEALTHYWORKERSREQUEST']._serialized_start=179
  _globals['_GETHEALTHYWORKERSREQUEST']._serialized_end=205
  _globals['_GETHEALTHYWORKERSRESPONSE']._serialized_start=207
  _globals['_GETHEALTHYWORKERSRESPONSE']._serialized_end=294
  _globals['_INTERNALMASTERSERVICE']._serialized_start=297
  _globals['_INTERNALMASTERSERVICE']._serialized_end=428
# @@protoc_insertion_point(module_scope)
