# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import master_health_interface_pb2 as master__health__interface__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in master_health_interface_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InternalMasterServiceStub(object):
    """Service for internal communication between master components
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealthyWorkers = channel.unary_unary(
                '/master_internal.InternalMasterService/GetHealthyWorkers',
                request_serializer=master__health__interface__pb2.GetHealthyWorkersRequest.SerializeToString,
                response_deserializer=master__health__interface__pb2.GetHealthyWorkersResponse.FromString,
                _registered_method=True)


class InternalMasterServiceServicer(object):
    """Service for internal communication between master components
    """

    def GetHealthyWorkers(self, request, context):
        """RPC for the main master server to get a list of healthy workers from the health monitor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalMasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealthyWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealthyWorkers,
                    request_deserializer=master__health__interface__pb2.GetHealthyWorkersRequest.FromString,
                    response_serializer=master__health__interface__pb2.GetHealthyWorkersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'master_internal.InternalMasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('master_internal.InternalMasterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InternalMasterService(object):
    """Service for internal communication between master components
    """

    @staticmethod
    def GetHealthyWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/master_internal.InternalMasterService/GetHealthyWorkers',
            master__health__interface__pb2.GetHealthyWorkersRequest.SerializeToString,
            master__health__interface__pb2.GetHealthyWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
